import getDatabasePool from '../db.js'
const fields = ['first_name','middle_name','last_name','gender','date_of_birth','mobile_number','whatsapp_number','aadhaar_number','occupation','education','address','village_id','taluka_id','district','pincode','registration_date','worker_card_number','card_issue_date','card_expiry_date','physical_verification_date','nominee_name','nominee_relation','bank_name','branch_name','account_number','ifsc_code','remarks','current_status']
const nullable = new Set(fields.filter((f) => !['first_name','last_name','mobile_number','aadhaar_number','registration_date','district','current_status'].includes(f)))
const workerSelect = `SELECT w.*, CONCAT_WS(' ',w.first_name,w.middle_name,w.last_name) full_name, v.name village_name, t.name taluka_name FROM workers w LEFT JOIN villages v ON v.id=w.village_id LEFT JOIN talukas t ON t.id=w.taluka_id`
function data(input) { return fields.reduce((out,key) => ({...out,[key]: input[key] === '' && nullable.has(key) ? null : input[key] ?? (nullable.has(key) ? null : undefined)}), {}) }
export async function ensureNoDuplicate(input, ignoredId = null) { const pool=getDatabasePool(); const [rows]=await pool.execute(`SELECT id,worker_code,first_name,last_name FROM workers WHERE (aadhaar_number=? OR mobile_number=? OR (worker_card_number IS NOT NULL AND worker_card_number=?)) ${ignoredId?'AND id != ?':''} LIMIT 1`, ignoredId?[input.aadhaar_number,input.mobile_number,input.worker_card_number||null,ignoredId]:[input.aadhaar_number,input.mobile_number,input.worker_card_number||null]); return rows[0] }
export async function createWorker(input,userId) { const pool=getDatabasePool(); const item=data(input); const [seed]=await pool.execute('INSERT INTO workers(worker_code,first_name,last_name,mobile_number,aadhaar_number,registration_date,created_by,updated_by) VALUES(?,?,?,?,?,?,?,?)',['TMP',item.first_name,item.last_name,item.mobile_number,item.aadhaar_number,item.registration_date,userId,userId]); const code=`RDGWU-${String(seed.insertId).padStart(6,'0')}`; const keys=Object.keys(item).filter((key)=>item[key]!==undefined); await pool.execute(`UPDATE workers SET worker_code=?, ${keys.map((k)=>`${k}=?`).join(', ')}, updated_by=? WHERE id=?`,[code,...keys.map((key)=>item[key]),userId,seed.insertId]); return getWorker(seed.insertId) }
export async function getWorker(id) { const pool=getDatabasePool(); const [rows]=await pool.execute(`${workerSelect} WHERE w.id=?`,[id]); return rows[0] }
export async function listWorkers(query) { const pool=getDatabasePool(); const where=[];const params=[];if(query.search){where.push('(CONCAT_WS(\' \',w.first_name,w.middle_name,w.last_name) LIKE ? OR w.mobile_number LIKE ? OR w.worker_code LIKE ? OR w.worker_card_number LIKE ? OR w.aadhaar_number LIKE ? OR v.name LIKE ? OR t.name LIKE ?)');params.push(...Array(7).fill(`%${query.search}%`))} for(const key of ['village_id','taluka_id','gender','current_status'])if(query[key]){where.push(`w.${key}=?`);params.push(query[key])} if(query.pending_verification==='true')where.push('(w.physical_verification_date IS NULL)'); if(query.card_expiry==='expired')where.push('(w.card_expiry_date < CURDATE())'); const page=Math.max(1,Number(query.page)||1), limit=Math.min(100,Math.max(10,Number(query.limit)||10)), order={alphabetical:'full_name ASC',newest:'w.created_at DESC',oldest:'w.created_at ASC',registration_date:'w.registration_date DESC',card_expiry:'w.card_expiry_date ASC',age:'w.date_of_birth ASC',village:'v.name ASC',taluka:'t.name ASC'}[query.sort]||'w.created_at DESC';const clause=where.length?` WHERE ${where.join(' AND ')}`:'';const [[count]]=await pool.execute(`SELECT COUNT(*) total FROM workers w LEFT JOIN villages v ON v.id=w.village_id LEFT JOIN talukas t ON t.id=w.taluka_id${clause}`,params);const [rows]=await pool.execute(`${workerSelect}${clause} ORDER BY ${order} LIMIT ? OFFSET ?`,[...params,limit,(page-1)*limit]);return {rows,pagination:{page,limit,total:count.total,pages:Math.ceil(count.total/limit)}} }
export async function updateWorker(id,input,userId){const pool=getDatabasePool();const item=data(input);const keys=Object.keys(item).filter((key)=>item[key]!==undefined);await pool.execute(`UPDATE workers SET ${keys.map((key)=>`${key}=?`).join(', ')}, updated_by=? WHERE id=?`,[...keys.map((key)=>item[key]),userId,id]);return getWorker(id)}
export async function removeWorker(id){const pool=getDatabasePool();return pool.execute('DELETE FROM workers WHERE id=?',[id])}
export async function dashboardStats(){const pool=getDatabasePool();const [[rows]]=await pool.execute(`SELECT COUNT(*) total_workers,SUM(current_status='active') active_workers,SUM(card_expiry_date<CURDATE()) expired_cards,SUM(physical_verification_date IS NULL) pending_verification FROM workers`);const [[applications]]=await pool.execute(`SELECT COUNT(*) pending_applications FROM applications WHERE status='pending'`);return {...rows,...applications}}
export async function addDocuments(workerId, files, userId){const pool=getDatabasePool();for(const file of files)await pool.execute('INSERT INTO worker_documents(worker_id,document_type,original_name,storage_path,mime_type,file_size,created_by) VALUES(?,?,?,?,?,?,?)',[workerId,file.fieldname,file.originalname,file.path,file.mimetype,file.size,userId]);return listDocuments(workerId)}
export async function listDocuments(workerId){const pool=getDatabasePool();const[rows]=await pool.execute('SELECT id,document_type,original_name,mime_type,file_size,created_at FROM worker_documents WHERE worker_id=? ORDER BY created_at DESC',[workerId]);return rows}
export async function documentPath(id){const pool=getDatabasePool();const[rows]=await pool.execute('SELECT storage_path,original_name,mime_type FROM worker_documents WHERE id=?',[id]);return rows[0]}
