import { Router } from 'express'
import getDatabasePool from '../db.js'
import { authenticate, authorizeRoles } from '../middleware/authMiddleware.js'
const router=Router(),clean=v=>String(v||'').trim().slice(0,5000)
router.get('/content',async(req,res,next)=>{try{const p=getDatabasePool(),lang=req.query.lang==='en'?'en':'mr';const[content]=await p.execute('SELECT content_key,title,body,language_code FROM site_content WHERE is_published=1 AND language_code IN (?,\'mr\') ORDER BY language_code DESC',[lang]);const[schemes]=await p.execute('SELECT * FROM public_schemes WHERE is_active=1 ORDER BY display_order,id');const[news]=await p.execute('SELECT * FROM news_announcements WHERE is_active=1 AND publish_date<=CURDATE() AND (expiry_date IS NULL OR expiry_date>=CURDATE()) ORDER BY is_featured DESC,publish_date DESC LIMIT 10');const[reviews]=await p.execute("SELECT name,message,rating,created_at FROM feedback WHERE feedback_type='review' AND is_public=1 ORDER BY created_at DESC LIMIT 10");const[[stats]]=await p.execute("SELECT (SELECT COUNT(*) FROM workers) workers,(SELECT COUNT(*) FROM card_renewals) renewals,(SELECT COUNT(*) FROM scholarships) scholarships");res.json({content,schemes,news,reviews,stats})}catch(e){next(e)}})
router.get('/notices',async(_req,res,next)=>{try{const[rows]=await getDatabasePool().execute('SELECT id,title_mr,title_en,description,category,publish_date,expiry_date,attachment_type,attachment_path,is_featured,display_order FROM notices WHERE is_active=1 AND publish_date<=CURDATE() AND (expiry_date IS NULL OR expiry_date>=CURDATE()) ORDER BY is_featured DESC,display_order,publish_date DESC');res.json({rows})}catch(e){next(e)}})
router.post('/feedback',async(req,res,next)=>{try{const b=req.body;if(!['feedback','complaint','problem','suggestion','review'].includes(b.feedback_type))return res.status(400).json({message:'Invalid feedback type.'});if(!clean(b.name)||!clean(b.message))return res.status(400).json({message:'Name and message are required.'});const p=getDatabasePool();await p.execute('INSERT INTO feedback(name,mobile,feedback_type,message,rating,registration_number) VALUES(?,?,?,?,?,?)',[clean(b.name).slice(0,150),clean(b.mobile).slice(0,20),b.feedback_type,clean(b.message),Number(b.rating)||null,clean(b.registration_number).slice(0,100)]);res.status(201).json({message:'Thank you for your feedback.'})}catch(e){next(e)}})
router.use(authenticate,authorizeRoles('admin'))
router.get('/cms/:table',async(req,res,next)=>{try{const allowed=['site_content','public_schemes','gallery_items','news_announcements','feedback','festival_messages'];if(!allowed.includes(req.params.table))return res.sendStatus(404);const[rows]=await getDatabasePool().query(`SELECT * FROM ${req.params.table} ORDER BY id DESC`);res.json({rows})}catch(e){next(e)}})
router.post('/cms/content',async(req,res,next)=>{try{const b=req.body;await getDatabasePool().execute('INSERT INTO site_content(content_key,language_code,title,body,updated_by) VALUES(?,?,?,?,?) ON DUPLICATE KEY UPDATE title=VALUES(title),body=VALUES(body),updated_by=VALUES(updated_by)',[b.content_key,b.language_code,b.title||null,b.body||null,req.user.sub]);res.sendStatus(204)}catch(e){next(e)}})
router.post('/cms/notices',async(req,res,next)=>{try{const b=req.body;await getDatabasePool().execute('INSERT INTO notices(title_mr,title_en,description,category,publish_date,expiry_date,attachment_type,attachment_path,is_active,is_featured,display_order,created_by) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)',[clean(b.title_mr).slice(0,255),clean(b.title_en).slice(0,255)||null,clean(b.description),clean(b.category).slice(0,100)||null,b.publish_date,b.expiry_date||null,b.attachment_type||null,clean(b.attachment_path).slice(0,500)||null,b.is_active!==false,Boolean(b.is_featured),Number(b.display_order)||0,req.user.sub]);res.sendStatus(201)}catch(e){next(e)}})
router.put('/cms/notices/:id',async(req,res,next)=>{try{const b=req.body;await getDatabasePool().execute('UPDATE notices SET title_mr=?,title_en=?,description=?,category=?,publish_date=?,expiry_date=?,attachment_type=?,attachment_path=?,is_active=?,is_featured=?,display_order=? WHERE id=?',[clean(b.title_mr).slice(0,255),clean(b.title_en).slice(0,255)||null,clean(b.description),clean(b.category).slice(0,100)||null,b.publish_date,b.expiry_date||null,b.attachment_type||null,clean(b.attachment_path).slice(0,500)||null,b.is_active!==false,Boolean(b.is_featured),Number(b.display_order)||0,req.params.id]);res.sendStatus(204)}catch(e){next(e)}})
router.delete('/cms/notices/:id',async(req,res,next)=>{try{await getDatabasePool().execute('DELETE FROM notices WHERE id=?',[req.params.id]);res.sendStatus(204)}catch(e){next(e)}})
export default router
