import bcrypt from 'bcrypt'
import { Router } from 'express'
import getDatabasePool from '../db.js'
import { authenticate, authorizeRoles } from '../middleware/authMiddleware.js'
import { validateStaff } from '../validation/staffValidation.js'
const router=Router();router.use(authenticate,authorizeRoles('admin'))
const fields='id,full_name,username,email,mobile_number,role,is_active,last_login_at,created_at,updated_at'
router.get('/',async(req,res,next)=>{try{const page=Math.max(1,+req.query.page||1),limit=Math.min(100,Math.max(10,+req.query.limit||10)),search=req.query.search?`%${req.query.search}%`:null;const pool=getDatabasePool();const where=search?' WHERE full_name LIKE ? OR username LIKE ? OR email LIKE ? OR mobile_number LIKE ?':'';const params=search?[search,search,search,search]:[];const [[count]]=await pool.execute(`SELECT COUNT(*) total FROM users${where}`,params);const[rows]=await pool.query(`SELECT ${fields} FROM users${where} ORDER BY created_at DESC LIMIT ${limit} OFFSET ${(page-1)*limit}`,params);res.json({rows,pagination:{page,limit,total:count.total,pages:Math.ceil(count.total/limit)}})}catch(e){next(e)}})
router.post('/',async(req,res,next)=>{try{const error=validateStaff(req.body,{creating:true});if(error)return res.status(400).json({message:error});const pool=getDatabasePool();const hash=await bcrypt.hash(req.body.password,12);const[result]=await pool.execute('INSERT INTO users(full_name,username,email,mobile_number,password_hash,role,is_active) VALUES(?,?,?,?,?,?,?)',[req.body.full_name,req.body.username,req.body.email.toLowerCase(),req.body.mobile_number||null,hash,req.body.role||'viewer',req.body.is_active!==false]);const[rows]=await pool.execute(`SELECT ${fields} FROM users WHERE id=?`,[result.insertId]);res.status(201).json(rows[0])}catch(e){if(e.code==='ER_DUP_ENTRY')return res.status(409).json({message:'Username, email, or mobile number already exists.'});next(e)}})
router.put('/:id',async(req,res,next)=>{try{const error=validateStaff(req.body);if(error)return res.status(400).json({message:error});const pool=getDatabasePool();const values=[req.body.full_name,req.body.username,req.body.email.toLowerCase(),req.body.mobile_number||null,req.body.role,req.body.is_active!==false,req.params.id];await pool.execute('UPDATE users SET full_name=?,username=?,email=?,mobile_number=?,role=?,is_active=? WHERE id=?',values);const[rows]=await pool.execute(`SELECT ${fields} FROM users WHERE id=?`,[req.params.id]);if(!rows[0])return res.status(404).json({message:'Staff member not found.'});res.json(rows[0])}catch(e){if(e.code==='ER_DUP_ENTRY')return res.status(409).json({message:'Username, email, or mobile number already exists.'});next(e)}})
router.patch('/:id/status',async(req,res,next)=>{try{const pool=getDatabasePool();await pool.execute('UPDATE users SET is_active=? WHERE id=?',[Boolean(req.body.is_active),req.params.id]);res.status(204).end()}catch(e){next(e)}})
router.post('/:id/reset-password',async(req,res,next)=>{try{const error=validateStaff(req.body,{creating:true});if(error)return res.status(400).json({message:error});const pool=getDatabasePool();await pool.execute('UPDATE users SET password_hash=? WHERE id=?',[await bcrypt.hash(req.body.password,12),req.params.id]);res.status(204).end()}catch(e){next(e)}})
router.delete('/:id',async(req,res,next)=>{try{if(String(req.user.sub)===String(req.params.id))return res.status(400).json({message:'You cannot delete your own account.'});const pool=getDatabasePool();const[result]=await pool.execute('DELETE FROM users WHERE id=?',[req.params.id]);if(!result.affectedRows)return res.status(404).json({message:'Staff member not found.'});res.status(204).end()}catch(e){next(e)}})
export default router
